// js/citation-figure.js -- GENERATED. Do not edit this file.
// Written by citation-figure/emit.py --place in the support repository
// from its citation-figure.js; edit that and re-emit.

// Citation figure: the dialog and the hover layer.
//
// Progressive enhancement over a plain link. Without this script -- or in
// an engine without <dialog>.showModal() -- the "Open the full figure" link
// opens the standalone SVG, which the browser shows at full size to pan and
// zoom. With it, the same file is fetched once and set inline in a dialog,
// because a hover layer needs the drawing inside the page's own document:
// an SVG opened through a link or an <img> is sealed off from the page's
// script and styles.
//
// Loaded, deferred, by the figure's include and by no other page. Dialog
// handling follows initPerfPlate() in js/main.js. Concepts named where they
// are used: fetch with async/await, DOMParser, event delegation, the top
// layer.

function initCitationFigure() {
  // Every link with this class opens the one dialog: the caption's link
  // under the figure, and any the entry's own prose carries.
  const links = document.querySelectorAll('.citation-figure-open');
  if (!links.length || typeof HTMLDialogElement !== 'function' ||
      typeof HTMLDialogElement.prototype.showModal !== 'function') return;

  // The dialog is built on the first click and kept. `building` holds that
  // first build's Promise, so a second click while the file is still
  // arriving waits for the same dialog instead of building another.
  let building = null;
  const open = async (e) => {
    e.preventDefault();
    const href = e.currentTarget.href;
    try {
      building ??= buildDialog(href);
      (await building).showModal();
    } catch (err) {
      // The link still works: fall back to opening the file itself.
      console.error(err);
      window.location.href = href;
    }
  };
  for (const link of links) link.addEventListener('click', open);
}

// `async` lets the function wait on a Promise with `await` and read top to
// bottom; it returns a Promise itself, which the click handler awaits.
async function buildDialog(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url}: ${res.status}`);
  const markup = await res.text();

  // Parse the file as SVG, not HTML, then bring the element into the page.
  const doc = new DOMParser().parseFromString(markup, 'image/svg+xml');
  if (doc.querySelector('parsererror')) throw new Error(`${url}: not well-formed SVG`);
  const svg = document.importNode(doc.documentElement, true);

  const dialog = document.createElement('dialog');
  dialog.className = 'citation-figure-dialog';
  dialog.setAttribute('closedby', 'any');
  dialog.setAttribute('aria-labelledby', 'cf-dialog-title');
  dialog.innerHTML = `
    <div class="cf-dialog-head">
      <h2 id="cf-dialog-title">Citations from the September posts</h2>
      <button type="button" class="cf-dialog-close" aria-label="Close">&times;</button>
    </div>
    <p class="cf-readout" aria-live="polite"></p>
    <div class="cf-dialog-pane"></div>`;
  dialog.querySelector('.cf-dialog-pane').append(svg);
  document.body.append(dialog);

  dialog.querySelector('.cf-dialog-close').addEventListener('click', () => dialog.close());
  // Light dismiss where closedby="any" is unimplemented: initPerfPlate's
  // test, unchanged.
  if (!('closedBy' in HTMLDialogElement.prototype)) {
    dialog.addEventListener('click', (e) => {
      if (e.target !== dialog) return;
      const box = dialog.getBoundingClientRect();
      const inside = e.clientX >= box.left && e.clientX <= box.right
                  && e.clientY >= box.top && e.clientY <= box.bottom;
      if (!inside) dialog.close();
    });
  }
  wireIsolation(svg, dialog.querySelector('.cf-readout'));
  return dialog;
}

// Point at, tap, or tab to a node: its lines and the nodes at their other
// ends stay at full strength and everything else fades.
function wireIsolation(svg, readout) {
  const HINT = 'Point at or tap a mark to isolate its links; Tab moves through the recent posts.';
  const nodes = [...svg.querySelectorAll('.nodes [data-id]')];
  const edges = [...svg.querySelectorAll('.edges [data-s]')];
  const byId = new Map(nodes.map(n => [n.dataset.id, n]));

  // Adjacency, built once: node id -> the lines that touch it.
  const touching = new Map(nodes.map(n => [n.dataset.id, []]));
  for (const e of edges) {
    touching.get(e.dataset.s).push(e);
    touching.get(e.dataset.t).push(e);
  }

  // The recent posts take keyboard focus. The sources answer to a pointer
  // only: a tab stop apiece would make the dialog a trap.
  for (const n of nodes) {
    if (n.dataset.c !== 'r') continue;
    n.setAttribute('tabindex', '0');
    n.setAttribute('aria-label', n.querySelector('title')?.textContent ?? '');
  }

  let current = null;
  function isolate(id) {
    if (id === current) return;
    clear();
    current = id;
    svg.classList.add('cf-isolating');
    byId.get(id).classList.add('on', 'cf-focus');
    for (const e of touching.get(id)) {
      e.classList.add('on');
      byId.get(e.dataset.s).classList.add('on');
      byId.get(e.dataset.t).classList.add('on');
    }
    const k = touching.get(id).length;
    const name = byId.get(id).querySelector('title')?.textContent ?? '';
    readout.textContent = `${name}: ${k} link${k === 1 ? '' : 's'}`;
  }
  function clear() {
    if (current === null) return;
    svg.classList.remove('cf-isolating');
    for (const el of svg.querySelectorAll('.on')) el.classList.remove('on', 'cf-focus');
    current = null;
    readout.textContent = HINT;
  }
  readout.textContent = HINT;

  // Event delegation: one listener on the whole drawing asks which shape the
  // event came from (closest), instead of a listener on every shape.
  const nodeOf = (e) => e.target.closest?.('[data-id]');
  svg.addEventListener('pointerover', (e) => {
    const n = nodeOf(e);
    if (n) isolate(n.dataset.id); else clear();
  });
  svg.addEventListener('pointerleave', clear);
  svg.addEventListener('focusin', (e) => { const n = nodeOf(e); if (n) isolate(n.dataset.id); });
  svg.addEventListener('focusout', clear);
}

// A deferred script runs after the document is parsed and before
// DOMContentLoaded fires, so the listener is registered in time.
document.addEventListener('DOMContentLoaded', initCitationFigure);
