/**
 * GIF slug map -- alt-text source for the 150x800 sidebar strips.
 *
 * The strips ship as 800abstract00001.gif .. 800abstract00120.gif, a naming
 * scheme that replaced the author's own descriptive filenames. This array
 * restores those names: index i corresponds to 800abstract00<i+1 padded to 3>.
 * The mapping was recovered 2026-08-18 by MD5-matching the 120 archive files
 * against the 120 repository files in alphabetical order -- 120 matches, 0
 * mismatches, 120 unique hashes, so the correspondence is exact and not a guess.
 *
 * Alt text is composed as: 'abstract gray and green image - ' + slug.
 * Ruled 2026-08-18 (Michael).
 */

const GIF_SLUGS = [
  "alarm",
  "anothermeadow",
  "arabic",
  "arch",
  "b24",
  "bed",
  "blackchairs",
  "blaze",
  "blobs",
  "bolt",
  "breathe",
  "carbomb",
  "chainlink",
  "chinook",
  "chippendale",
  "concessions",
  "container",
  "corrugation",
  "cross",
  "curve",
  "curveship",
  "deadpool",
  "dendriticblur",
  "dia1",
  "ditherhall",
  "doorway",
  "drivedive",
  "duskmeadow",
  "elevator",
  "emperor",
  "factory1",
  "fan",
  "fireforeffect",
  "flame",
  "foolonthehill",
  "forestedge",
  "ghostfence",
  "glow",
  "grid",
  "gulls",
  "gunport",
  "hamptonwires",
  "harlemtrain",
  "harlemtrains2",
  "hedge",
  "honor",
  "hotelskew",
  "hothouse",
  "hotround",
  "huey",
  "ivytable",
  "jkiframe",
  "kabul_desk",
  "lampandjade",
  "lewis1",
  "lewis2",
  "library10th",
  "librarywindow",
  "lifeguard",
  "lovecraft",
  "masons",
  "mordor",
  "morse1",
  "morse2",
  "morse3",
  "morse4",
  "nightmareroom",
  "parklight",
  "patchy",
  "payphone",
  "pillar",
  "plane",
  "post",
  "prospector2",
  "pulley",
  "railing",
  "ronald",
  "sacrifice",
  "scaryhall",
  "silos",
  "sinkandtowels",
  "skatepark",
  "snowwires",
  "snowydeck",
  "snowyroad",
  "spookyforest",
  "spring",
  "ssl1",
  "ssl2",
  "ssl3",
  "stadium1",
  "stairs",
  "station",
  "sticks",
  "streetlight",
  "supermarket",
  "swings",
  "switches",
  "tablecurlicue",
  "tenement",
  "thrudoor",
  "tiltyhall",
  "track",
  "trackplants",
  "tracks",
  "tracks2",
  "trailermattress",
  "train",
  "truckback",
  "twigfour",
  "twigthree",
  "twigtwo",
  "unholy",
  "viewfromabove",
  "violentsky",
  "wall",
  "wires",
  "wires2",
  "witch",
  "witherblister"
];

/**
 * Build the alt text for a strip, given its zero-based index.
 * @param {number} i - Zero-based index into GIF_SLUGS (0..119).
 * @returns {string} Alt text, or a generic fallback if the index is out of range.
 */
function gifAltText(i) {
  const slug = GIF_SLUGS[i];
  return slug ? `abstract gray and green image - ${slug}` : 'abstract gray and green image';
}
