---
layout: null
# Generated at build from _data/taglines.yml. Do not edit this file -- edit
# the data. The front matter is what makes Jekyll process the Liquid below;
# without it the template ships to the browser verbatim.
#
# `layout: null` is required and is not the ruled-against case. _config.yml
# defaults `layout: page` to every file Jekyll reads as a page, and a file
# with front matter is one whatever its extension -- so the first build of
# this file wrapped the script in the site's full HTML chrome (found and
# fixed 2026-08-23). The 2026-08-19 ruling that a source never asserts its
# layout governs page sources; this declines a layout rather than choosing
# one. A conformance pass must not strip it.
---
/**
 * Taglines. The array is written by Jekyll from _data/taglines.yml, which is
 * the single source; main.js reads TAGLINES and re-draws one per page load.
 * The build also writes one into the markup as the no-JavaScript baseline --
 * see _includes/tagline.html -- so the two mechanisms are a floor and a
 * refinement rather than alternatives.
 */
const TAGLINES = {{ site.data.taglines | jsonify }};
